
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';


export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';


export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';


